model:
  path: models/best.pt

video:
  input: input/klip2_4.40-5.00_slow0.8x.mp4
  output: output/videos/output_klip2_4.40-5.00_bytetrack_no_smoothing.mp4
#yol_videosu_klip1_3.20-3.45.mp4
#yol_videosu_klip2_4.40-5.00.mp4
#yol_videosu_klip3_6.10-6.30.mp4
#yol_videosu_klip4_7.00-7.25.mp4
#cok_kotu.mp4
tracking:
  backend: ultralytics
  tracker: bytetrack.yaml
  conf: 0.15
  imgsz: 640
  n_confirm: 3
  m_persist: 5
  device: 0

smoothing:
  type: none
  alpha: 0.5

output:
  csv: output/csv/output_bytetrack_no_smoothing.csv
  log: output/logs/pipeline_bytetrack_no_smoothing.log
  benchmark_csv: output/benchmarks/results.csv

roi:
  points:
    - [0.38, 0.55]
    - [0.62, 0.55]
    - [1.00, 0.85]
    - [0.00, 0.85]

visualization:
  draw_mask: true
  draw_roi: true